var mobileDevice = false;
if(
	navigator.userAgent.match(/Android/i) ||
	navigator.userAgent.match(/webOS/i) ||
	navigator.userAgent.match(/iPhone/i) ||
	navigator.userAgent.match(/iPad/i) ||
	navigator.userAgent.match(/iPod/i))
{
	mobileDevice = true;
}
if (!mobileDevice) {
	galleryDef = [	// Slideshow Data
		{type : 'img', image : 'img/gallery/fashion/fashion1.jpg', title : "<h1>gravida <span>commodo</span></h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis. Aliquam dignissim malesuada pharetra. Fusce volutpat ipsum gravida lacus interdum suscipit. Ut porta odio sed massa vestibulum viverra.</p>", thumb : 'img/gallery/fashion/thmb/fashion1.jpg', url : ''},	
		{type : 'img', image : 'img/gallery/fashion/fashion2.jpg', title : "<h1>sapien <span>in</span></h1><br><p>Fusce id sapien dolor, nec commodo arcu. Ut risus, commodo in gravida in, vehicula</p>", thumb : 'img/gallery/fashion/thmb/fashion2.jpg', url : ''},
		{type : 'video', subtype : 'youtube', src : 'oR53gDOeOpQ', title : "<h1>commodo <span>vehicula</span></h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis. Aliquam dignissim malesuada pharetra. Fusce volutpat ipsum gravida lacus interdum suscipit. Ut porta odio sed massa vestibulum viverra.</p>", thumb : 'img/gallery/fashion/thmb/fashion3.jpg'},
		{type : 'img', image : 'img/gallery/fashion/fashion4.jpg', title : "<h1>gravida <span>commodo</span></h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis. Aliquam dignissim malesuada pharetra. Fusce volutpat ipsum gravida lacus interdum suscipit. Ut porta odio sed massa vestibulum viverra.</p>", thumb : 'img/gallery/fashion/thmb/fashion4.jpg', url : ''},	
		{type : 'video', subtype : 'youtube', src : 'LR6Xpd8nwPs', title : "<h1>commodo <span>vehicula</span></h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis. Aliquam dignissim malesuada pharetra. Fusce volutpat ipsum gravida lacus interdum suscipit. Ut porta odio sed massa vestibulum viverra.</p>", thumb : 'img/gallery/fashion/thmb/fashion5.jpg'},
		{type : 'img', image : 'img/gallery/fashion/fashion6.jpg', title : "<h1>vehicula <span>id</span></h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis. Aliquam dignissim malesuada pharetra. Fusce volutpat ipsum gravida lacus interdum suscipit. Ut porta odio sed massa vestibulum viverra.</p>", thumb : 'img/gallery/fashion/thmb/fashion6.jpg', url : ''},	
		{type : 'img', image : 'img/gallery/fashion/fashion7.jpg', title : "<h1>enim <span>elit</span></h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis. Aliquam dignissim malesuada pharetra. Fusce volutpat ipsum gravida lacus interdum suscipit. Ut porta odio sed massa vestibulum viverra.</p>", thumb : 'img/gallery/fashion/thmb/fashion7.jpg', url : ''},	
		{type : 'img', image : 'img/gallery/fashion/fashion8.jpg', title : "<h1>Integer</h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis. Aliquam dignissim malesuada pharetra. Fusce volutpat ipsum gravida lacus interdum suscipit. Ut porta odio sed massa vestibulum viverra.</p>", thumb : 'img/gallery/fashion/thmb/fashion8.jpg', url : ''},	
		{type : 'img', image : 'img/gallery/fashion/fashion9.jpg', title : "<h1>mattis  <span>vitae </span></h1><br><p>Fusce id sapien dolor, nec commodo arcu. Ut risus, commodo in gravida in, vehicula</p>", thumb : 'img/gallery/fashion/thmb/fashion9.jpg', url : ''},	
		{type : 'img', image : 'img/gallery/fashion/fashion10.jpg', title : "<h1>sit  <span>amet</span></h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis. Aliquam dignissim malesuada pharetra. Fusce volutpat ipsum gravida lacus interdum suscipit.</p>", thumb : 'img/gallery/fashion/thmb/fashion10.jpg', url : ''},	
		{type : 'img', image : 'img/gallery/fashion/fashion11.jpg', title : "<h1>sapien <span>in</span></h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis.</p>", thumb : 'img/gallery/fashion/thmb/fashion11.jpg', url : ''},
		{type : 'img', image : 'img/gallery/fashion/fashion1.jpg', title : "<h1>gravida <span>commodo</span></h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis. Aliquam dignissim malesuada pharetra. Fusce volutpat ipsum gravida lacus interdum suscipit. Ut porta odio sed massa vestibulum viverra.</p>", thumb : 'img/gallery/fashion/thmb/fashion1.jpg', url : ''},	
		{type : 'img', image : 'img/gallery/fashion/fashion2.jpg', title : "<h1>sapien <span>in</span></h1><br><p>Fusce id sapien dolor, nec commodo arcu. Ut risus, commodo in gravida in, vehicula</p>", thumb : 'img/gallery/fashion/thmb/fashion2.jpg', url : ''},
		{type : 'video', subtype : 'youtube', src : 'oR53gDOeOpQ', title : "<h1>commodo <span>vehicula</span></h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis. Aliquam dignissim malesuada pharetra. Fusce volutpat ipsum gravida lacus interdum suscipit. Ut porta odio sed massa vestibulum viverra.</p>", thumb : 'img/gallery/fashion/thmb/fashion3.jpg'},
		{type : 'img', image : 'img/gallery/fashion/fashion4.jpg', title : "<h1>gravida <span>commodo</span></h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis. Aliquam dignissim malesuada pharetra. Fusce volutpat ipsum gravida lacus interdum suscipit. Ut porta odio sed massa vestibulum viverra.</p>", thumb : 'img/gallery/fashion/thmb/fashion4.jpg', url : ''},	
		{type : 'video', subtype : 'youtube', src : 'LR6Xpd8nwPs', title : "<h1>commodo <span>vehicula</span></h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis. Aliquam dignissim malesuada pharetra. Fusce volutpat ipsum gravida lacus interdum suscipit. Ut porta odio sed massa vestibulum viverra.</p>", thumb : 'img/gallery/fashion/thmb/fashion5.jpg'},
		{type : 'img', image : 'img/gallery/fashion/fashion6.jpg', title : "<h1>vehicula <span>id</span></h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis. Aliquam dignissim malesuada pharetra. Fusce volutpat ipsum gravida lacus interdum suscipit. Ut porta odio sed massa vestibulum viverra.</p>", thumb : 'img/gallery/fashion/thmb/fashion6.jpg', url : ''},	
		{type : 'img', image : 'img/gallery/fashion/fashion7.jpg', title : "<h1>enim <span>elit</span></h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis. Aliquam dignissim malesuada pharetra. Fusce volutpat ipsum gravida lacus interdum suscipit. Ut porta odio sed massa vestibulum viverra.</p>", thumb : 'img/gallery/fashion/thmb/fashion7.jpg', url : ''},	
		{type : 'img', image : 'img/gallery/fashion/fashion8.jpg', title : "<h1>Integer</h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis. Aliquam dignissim malesuada pharetra. Fusce volutpat ipsum gravida lacus interdum suscipit. Ut porta odio sed massa vestibulum viverra.</p>", thumb : 'img/gallery/fashion/thmb/fashion8.jpg', url : ''},	
		{type : 'img', image : 'img/gallery/fashion/fashion9.jpg', title : "<h1>mattis  <span>vitae </span></h1><br><p>Fusce id sapien dolor, nec commodo arcu. Ut risus, commodo in gravida in, vehicula</p>", thumb : 'img/gallery/fashion/thmb/fashion9.jpg', url : ''},	
		{type : 'img', image : 'img/gallery/fashion/fashion10.jpg', title : "<h1>sit  <span>amet</span></h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis. Aliquam dignissim malesuada pharetra. Fusce volutpat ipsum gravida lacus interdum suscipit.</p>", thumb : 'img/gallery/fashion/thmb/fashion10.jpg', url : ''},	
		{type : 'img', image : 'img/gallery/fashion/fashion11.jpg', title : "<h1>sapien <span>in</span></h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis.</p>", thumb : 'img/gallery/fashion/thmb/fashion11.jpg', url : ''}
	];
} else {
	galleryDef = [	// Slideshow Data
		{type : 'img', image : 'img/gallery/fashion/fashion1.jpg', title : "<h1>gravida <span>commodo</span></h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis. Aliquam dignissim malesuada pharetra. Fusce volutpat ipsum gravida lacus interdum suscipit. Ut porta odio sed massa vestibulum viverra.</p>", thumb : 'img/gallery/fashion/thmb/fashion1.jpg', url : ''},	
		{type : 'img', image : 'img/gallery/fashion/fashion2.jpg', title : "<h1>sapien <span>in</span></h1><br><p>Fusce id sapien dolor, nec commodo arcu. Ut risus, commodo in gravida in, vehicula</p>", thumb : 'img/gallery/fashion/thmb/fashion2.jpg', url : ''},
		{type : 'img', image : 'img/gallery/fashion/fashion4.jpg', title : "<h1>gravida <span>commodo</span></h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis. Aliquam dignissim malesuada pharetra. Fusce volutpat ipsum gravida lacus interdum suscipit. Ut porta odio sed massa vestibulum viverra.</p>", thumb : 'img/gallery/fashion/thmb/fashion4.jpg', url : ''},	
		{type : 'img', image : 'img/gallery/fashion/fashion6.jpg', title : "<h1>vehicula <span>id</span></h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis. Aliquam dignissim malesuada pharetra. Fusce volutpat ipsum gravida lacus interdum suscipit. Ut porta odio sed massa vestibulum viverra.</p>", thumb : 'img/gallery/fashion/thmb/fashion6.jpg', url : ''},	
		{type : 'img', image : 'img/gallery/fashion/fashion7.jpg', title : "<h1>enim <span>elit</span></h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis. Aliquam dignissim malesuada pharetra. Fusce volutpat ipsum gravida lacus interdum suscipit. Ut porta odio sed massa vestibulum viverra.</p>", thumb : 'img/gallery/fashion/thmb/fashion7.jpg', url : ''},	
		{type : 'img', image : 'img/gallery/fashion/fashion8.jpg', title : "<h1>Integer</h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis. Aliquam dignissim malesuada pharetra. Fusce volutpat ipsum gravida lacus interdum suscipit. Ut porta odio sed massa vestibulum viverra.</p>", thumb : 'img/gallery/fashion/thmb/fashion8.jpg', url : ''},	
		{type : 'img', image : 'img/gallery/fashion/fashion9.jpg', title : "<h1>mattis  <span>vitae </span></h1><br><p>Fusce id sapien dolor, nec commodo arcu. Ut risus, commodo in gravida in, vehicula</p>", thumb : 'img/gallery/fashion/thmb/fashion9.jpg', url : ''},	
		{type : 'img', image : 'img/gallery/fashion/fashion10.jpg', title : "<h1>sit  <span>amet</span></h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis. Aliquam dignissim malesuada pharetra. Fusce volutpat ipsum gravida lacus interdum suscipit.</p>", thumb : 'img/gallery/fashion/thmb/fashion10.jpg', url : ''},	
		{type : 'img', image : 'img/gallery/fashion/fashion11.jpg', title : "<h1>sapien <span>in</span></h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis.</p>", thumb : 'img/gallery/fashion/thmb/fashion11.jpg', url : ''},
		{type : 'img', image : 'img/gallery/fashion/fashion1.jpg', title : "<h1>gravida <span>commodo</span></h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis. Aliquam dignissim malesuada pharetra. Fusce volutpat ipsum gravida lacus interdum suscipit. Ut porta odio sed massa vestibulum viverra.</p>", thumb : 'img/gallery/fashion/thmb/fashion1.jpg', url : ''},	
		{type : 'img', image : 'img/gallery/fashion/fashion2.jpg', title : "<h1>sapien <span>in</span></h1><br><p>Fusce id sapien dolor, nec commodo arcu. Ut risus, commodo in gravida in, vehicula</p>", thumb : 'img/gallery/fashion/thmb/fashion2.jpg', url : ''},
		{type : 'img', image : 'img/gallery/fashion/fashion4.jpg', title : "<h1>gravida <span>commodo</span></h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis. Aliquam dignissim malesuada pharetra. Fusce volutpat ipsum gravida lacus interdum suscipit. Ut porta odio sed massa vestibulum viverra.</p>", thumb : 'img/gallery/fashion/thmb/fashion4.jpg', url : ''},	
		{type : 'img', image : 'img/gallery/fashion/fashion6.jpg', title : "<h1>vehicula <span>id</span></h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis. Aliquam dignissim malesuada pharetra. Fusce volutpat ipsum gravida lacus interdum suscipit. Ut porta odio sed massa vestibulum viverra.</p>", thumb : 'img/gallery/fashion/thmb/fashion6.jpg', url : ''},	
		{type : 'img', image : 'img/gallery/fashion/fashion7.jpg', title : "<h1>enim <span>elit</span></h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis. Aliquam dignissim malesuada pharetra. Fusce volutpat ipsum gravida lacus interdum suscipit. Ut porta odio sed massa vestibulum viverra.</p>", thumb : 'img/gallery/fashion/thmb/fashion7.jpg', url : ''},	
		{type : 'img', image : 'img/gallery/fashion/fashion8.jpg', title : "<h1>Integer</h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis. Aliquam dignissim malesuada pharetra. Fusce volutpat ipsum gravida lacus interdum suscipit. Ut porta odio sed massa vestibulum viverra.</p>", thumb : 'img/gallery/fashion/thmb/fashion8.jpg', url : ''},	
		{type : 'img', image : 'img/gallery/fashion/fashion9.jpg', title : "<h1>mattis  <span>vitae </span></h1><br><p>Fusce id sapien dolor, nec commodo arcu. Ut risus, commodo in gravida in, vehicula</p>", thumb : 'img/gallery/fashion/thmb/fashion9.jpg', url : ''},	
		{type : 'img', image : 'img/gallery/fashion/fashion10.jpg', title : "<h1>sit  <span>amet</span></h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis. Aliquam dignissim malesuada pharetra. Fusce volutpat ipsum gravida lacus interdum suscipit.</p>", thumb : 'img/gallery/fashion/thmb/fashion10.jpg', url : ''},	
		{type : 'img', image : 'img/gallery/fashion/fashion11.jpg', title : "<h1>sapien <span>in</span></h1><br><p>Cras molestie venenatis risus, eget vulputate urna tempor et. Suspendisse urna massa vehicula ut molestie vitae, sollicitudin sollicitudin dolor. Praesent massa lectus, faucibus nec euismod quis, luctus id turpis.</p>", thumb : 'img/gallery/fashion/thmb/fashion11.jpg', url : ''}
	];
}
jQuery(function($){
			
	$.supersized({
    	// Functionality
		slideshow               :   1,			// Slideshow on/off
		autoplay				:	1,			// Slideshow starts playing automatically
		start_slide             :   1,			// Start slide (0 is random)
		stop_loop				:	0,			// Stops slideshow on last slide
		random					: 	0,			// Randomize slide order (Ignores start slide)
		slide_interval          :   8000,		// Length between transitions
		transition              :   1, 			// 0-None, 1-Fade, 2-Slide Top, 3-Slide Right, 4-Slide Bottom, 5-Slide Left, 6-Carousel Right, 7-Carousel Left
		transition_speed		:	1000,		// Speed of transition
		new_window				:	1,			// Image links open in new window/tab
		pause_hover             :   0,			// Pause slideshow on hover
		keyboard_nav            :   1,			// Keyboard navigation on/off
		performance				:	2,			// 0-Normal, 1-Hybrid speed/quality, 2-Optimizes image quality, 3-Optimizes transition speed //  (Only works for Firefox/IE, not Webkit)
		image_protect			:	1,			// Disables image dragging and right click with Javascript
												   
		// Size & Position
		fit_always				:	0,			// Image will never exceed browser width or height (Ignores min. dimensions)
		fit_landscape			:   0,			// Landscape images will not exceed browser width
		fit_portrait         	:   1,			// Portrait images will not exceed browser height  			   
		min_width		        :   100,			// Min width allowed (in pixels)
		min_height		        :   100,			// Min height allowed (in pixels)
		horizontal_center       :   1,			// Horizontally center background
		vertical_center         :   1,			// Vertically center background
		
												   
		// Components							
		slide_links				:	1,			// Individual links for each slide (Options: false, 'num', 'name', 'blank')
		thumb_links				:	1,			// Individual thumb links for each slide
		thumbnail_navigation    :   0,			// Thumbnail navigation
		slides 					:  	galleryDef
		
	});
});